### ISSUE TITLE
Add support for Uyghur language.

### ISSUE THREAD

**Issue by MemetTursun** [notofonts/nastaliq#60]
Add support for Uyghur language.
 
The Nastaliq font is widely used in the Uyghur language. Handwriting, calligraphy, and often titles will still often use a Nastaliq script. Modern Uyghur still uses Arabic script and still will use a Nastaliq font.
 
The current hamza used over a vowel beginning a sentence also does not work in Uyghur as it would read as a ت. I have attached a hamza that would be used in a Uyghur nastaliq font.
 
06AD
FBD3 - ng-ar.isol
FBD5 - ng-ar.init
FBD6 - ng-ar.medi
FBD4 - ng-ar.fina
06CB
FBDE - ve-ar
FBDF - ve-ar.fina
06C8
FBDB - yu-ar.isol
FBDC - yu-ar.fina
0643 - kaf-ar.fina
06BE
FBAB - hehDoachashmee-ar.fina
FBAD - hehDoachashmee-ar.medi
FBAA - hehDoachashmee-ar.isol
uniFBF9 - uighurkirghizyehHamzaabove_alefMaksura-ar

![hamza](https://github.com/notofonts/nastaliq/assets/149747768/1c6b1c09-4739-4dd3-89cf-97cf7a8cbed1)
![0QJoei5UWPs](https://github.com/notofonts/nastaliq/assets/149747768/e05a1a1b-fc19-4fc4-8a62-5d2638febdc0)
![sdiekcp](https://github.com/notofonts/nastaliq/assets/149747768/54a69951-15f2-4a50-a60b-58f63e295e85)
![oiheejik](https://github.com/notofonts/nastaliq/assets/149747768/0a379bed-b878-43aa-a07f-cd56e98074d2)

**Comment by simoncozens** [comment]
It is possible to change the hamza style to Arabic-style hamzas, by setting the text language to Arabic. OpenType has a language tag for Uyghur, so the fix here is to add a Uyghur languagesystem and have that select the appropriate hamza shape.

**Comment by MemetTursun** [comment]
The waw based vowels (as well as waw itself) are lacking a final form. و ۇ ۈ ۆ ۋ Please let me know if you have any questions on the other errors. Thank you for taking the time. The correct text is underneath in blue.

![Image (1)](https://github.com/notofonts/nastaliq/assets/149747768/14affe45-3c1d-4f25-9454-b31875b3d1e4)

**Comment by simoncozens** [comment]
I think you must have an old version; this seems fine for me:
![shape](https://github.com/notofonts/nastaliq/assets/106728/b83c061c-409b-4c17-9dab-94360cc58a4f)

I'm not sure about the kaf issue. Can you paste me the actual text?

**Comment by MemetTursun** [comment]
#  ئالمايمەن مېنىڭ ئىگ ئىك مېنىڭكى بۈلۋۆلدى مىھدارمائاراپ پېئىل

**Comment by simoncozens** [comment]
Here's what I get:

![shape](https://github.com/notofonts/nastaliq/assets/106728/ac42ca2b-653c-402e-afa0-51ad35e24dda)

The word "مېنىڭ" is clearly wrong but the rest seems OK to me, unless I have missed something.

**Comment by simoncozens** [comment]
Fixed it, now we have:

![shape](https://github.com/notofonts/nastaliq/assets/106728/bddf23ec-4851-4441-8a28-eb90e4b32496)

**Comment by r12a** [comment]
> I think you must have an old version; this seems fine for me:

Here's what i'm seeing on macOS Ventura.  I installed v3.009 of the nastaliq font.

<p dir=rtl><img width="539" alt="Screenshot 2023-11-21 at 11 17 34" src="https://github.com/notofonts/nastaliq/assets/4839211/209954a0-f0de-42c0-be1b-0c9efbff250d"></p>

I thought that this might be caused by macOS using the pre-installed version of the font, which you can't delete  (grrrr).  So i made a webfont using fontsquirrel, but that turned out different again. It seems to be dropping glyphs from the font.

<p dir=rtl><img width="495" alt="Screenshot 2023-11-21 at 11 21 57" src="https://github.com/notofonts/nastaliq/assets/4839211/e2ff4920-0b41-453b-8288-632dabd1c760"></p>

**Comment by r12a** [comment]
> It is possible to change the hamza style to Arabic-style hamzas, by setting the text language to Arabic. OpenType has a language tag for Uyghur, so the fix here is to add a Uyghur languagesystem and have that select the appropriate hamza shape.

If i understand it correctly (maybe not) the recommendation here is to label the text as Arabic language text rather than Uighur(?).  That certainly works, but it doesn't seem like a good idea, since it affects other things (for example spell checking, hyphenation, etc.)

@simoncozens we previously changed the noto font for Kashmiri to create rounded hamzas rather than the Urdu s-shaped ones.  Can we not fix the font for Uighur in the same way.

Fwiw, here's what i see with the language set to ks.
<img width="114" alt="Screenshot 2023-11-21 at 11 31 33" src="https://github.com/notofonts/nastaliq/assets/4839211/fcda1963-9e3f-43ce-b5f0-62ef1cd9da8b">

**Comment by simoncozens** [comment]
> If i understand it correctly (maybe not) the recommendation here is to label the text as Arabic language text rather than Uighur(?). 

Until I fix it, yes.
