### ISSUE TITLE
Issue with Nastaliq Font in Android

### ISSUE THREAD

**Issue by Hassan-kareem** [notofonts/nastaliq#61]
Hii
Why isn't the beautiful Nastaliq font being used for Urdu language support in Android? It adds a unique touch and readability. Let's enhance the user experience! Any plans to integrate Nastaliq in future updates? 

And I've noticed an issue with Noto NastaliqUrdu font on Android. When I use it with Urdu language using fonts.xml, I experience text cutting (extra spaces) at the bottom. This doesn't happen when I use Noori Nastaliq Fonts. Any insights or solutions?🤔

See the Screenshots
<h2>Noori Nastaliq font</h2>

![Noori Nastaliq](https://github.com/notofonts/nastaliq/assets/144518310/0df67e59-df44-43ed-8a05-f2ac73a22630)
<br>
<h2>NotoNastaliqUrdu font</h2>

![NotoNastaliqUrdu](https://github.com/notofonts/nastaliq/assets/144518310/10d60eeb-7804-4821-950f-bb500b13b276)

**Comment by simoncozens** [comment]
I believe the reason why Android does not use Nastaliq is precisely because of the vertical metrics (clipping) issue you noted! But I think there are discussions going on about how to fix this and to use Nastaliq on Android (I think they also want to make sure all language support is good first).

 However, that is an issue for the Android team; I am only handle the development of the Nastaliq font itself.

**Comment by Hassan-kareem** [comment]
Okay. since i'm using these Noori nastaliq fonts it's not giving me any issue like this. i think they can fix it

[ForNotoNastaliqUrdu.zip](https://github.com/notofonts/nastaliq/files/13423208/ForNotoNastaliqUrdu.zip)
