### ISSUE TITLE
Need Help With Android font issue

### ISSUE THREAD

**Issue by Hassan-kareem** [notofonts/nastaliq#65]
Dear Sir, I'm facing an issue with the Noto Nastaliq Urdu font on Android, specifically related to fixing the clipping problem. The clipping issue was resolved by decreasing the size and yMax by 20%. However, a new problem emerged after the size reduction, particularly with the character ے. Please refer to the attached screenshot. Is there any solution to rectify this? Your help is greatly appreciated.

![Issue](https://github.com/notofonts/nastaliq/assets/144518310/aa73eb6e-3a4f-4e5f-91fb-c2055397a5b4)

**Comment by simoncozens** [comment]
You are unlikely to get good results by simply scaling this font down, because the layout rules apply positioning in font units. You may be able to do what you want by changing the font's vertical metrics (ascender and descender in the hhea and OS/2 tables), but this is not a supported use of the font!
